# Generated by Django 4.1.5 on 2023-01-24 17:33

import django.core.validators
from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1024)])),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1024)])),
                ('image_file', models.ImageField(upload_to=images.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'gif', 'bmp'))])),
            ],
        ),
    ]
