# Generated by Django 4.1.5 on 2023-01-21 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1024)])),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1024)])),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
    ]
